// Type Imports
import type { Booking } from '@/types/account/booking-types'

export const db: Booking[] = [
  {
    id: 'booking-001',
    packageSlug: 'bali-island-escape',
    packageTitle: 'Bali Island Escape',
    packageImage: '/images/countries/indonesia/indonesia-1.webp',
    packageLocation: 'Bali, Indonesia',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-08-15',
    bookingRef: 'TRV-DEM01-A1B2',
    totalAmount: 2398,
    paymentResult: { method: 'card', cardLast4: '7658' },
    bookedAt: '2026-06-02T09:15:00.000Z',
    status: 'upcoming',
    contactName: 'Mitchell Johnson',
    contactEmail: 'mitchell11@gmail.com',
    contactPhone: '+1 (555) 204-7788',
    travelersInfo: [
      {
        firstName: 'Mitchell',
        lastName: 'Johnson',
        email: 'mitchell11@gmail.com',
        phone: '+1 (555) 204-7788',
        age: 34,
        gender: 'male'
      },
      {
        firstName: 'Sarah',
        lastName: 'Johnson',
        email: 'sarah.johnson11@gmail.com',
        phone: '+1 (555) 204-7790',
        age: 31,
        gender: 'female'
      }
    ],
    couponCode: 'SUMMER20',
    discountAmount: 200,
    baseAmount: 2598,
    notes: 'Requested a vegetarian meal plan and early check-in at the resort.'
  },
  {
    id: 'booking-002',
    packageSlug: 'swiss-alps-adventure',
    packageTitle: 'Swiss Alps Adventure',
    packageImage: '/images/countries/switzerland/switzerland-1.webp',
    packageLocation: 'Interlaken, Switzerland',
    packageDays: 7,
    packageNights: 6,
    travelers: 1,
    travelDate: '2026-03-10',
    bookingRef: 'TRV-DEM02-C3D4',
    totalAmount: 1499,
    paymentResult: { method: 'card', cardLast4: '8489' },
    bookedAt: '2026-01-18T14:40:00.000Z',
    status: 'completed',
    contactName: 'Mitchell Johnson',
    contactEmail: 'mitchell11@gmail.com',
    contactPhone: '+1 (555) 204-7788',
    travelersInfo: [
      {
        firstName: 'Mitchell',
        lastName: 'Johnson',
        email: 'mitchell11@gmail.com',
        phone: '+1 (555) 204-7788',
        age: 34,
        gender: 'male'
      }
    ],
    baseAmount: 1499
  },
  {
    id: 'booking-003',
    packageSlug: 'bali-island-escape',
    packageTitle: 'Bali Island Escape',
    packageImage: '/images/countries/indonesia/indonesia-1.webp',
    packageLocation: 'Bali, Indonesia',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2026-06-22',
    bookingRef: 'TRV-0021-JBNA',
    totalAmount: 899,
    paymentResult: { method: 'card', cardLast4: '8104' },
    bookedAt: '2026-05-24T16:06:00.000Z',
    status: 'completed',
    contactName: 'Amelia Carter',
    contactEmail: 'amelia.carter@example.com',
    contactPhone: '+1 415-552-1187',
    contactAvatar: '/images/avatars/avatar-2.webp',
    baseAmount: 899
  },
  {
    id: 'booking-004',
    packageSlug: 'ubud-rice-terrace-retreat',
    packageTitle: 'Ubud Rice Terrace Retreat',
    packageImage: '/images/countries/indonesia/indonesia-2.webp',
    packageLocation: 'Ubud, Indonesia',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-09-22',
    bookingRef: 'TRV-0022-YRPB',
    totalAmount: 749,
    paymentResult: { method: 'card', cardLast4: '7499' },
    bookedAt: '2026-09-09T17:07:00.000Z',
    status: 'cancelled',
    contactName: 'Amelia Carter',
    contactEmail: 'amelia.carter@example.com',
    contactPhone: '+1 415-552-1187',
    contactAvatar: '/images/avatars/avatar-2.webp',
    baseAmount: 749
  },
  {
    id: 'booking-005',
    packageSlug: 'swiss-alps-adventure',
    packageTitle: 'Swiss Alps Adventure',
    packageImage: '/images/countries/switzerland/switzerland-1.webp',
    packageLocation: 'Interlaken, Switzerland',
    packageDays: 7,
    packageNights: 6,
    travelers: 1,
    travelDate: '2026-07-10',
    bookingRef: 'TRV-0023-NPPS',
    totalAmount: 2199,
    paymentResult: { method: 'card', cardLast4: '2688' },
    bookedAt: '2026-06-12T14:09:00.000Z',
    status: 'cancelled',
    contactName: 'Amelia Carter',
    contactEmail: 'amelia.carter@example.com',
    contactPhone: '+1 415-552-1187',
    contactAvatar: '/images/avatars/avatar-2.webp',
    baseAmount: 2199
  },
  {
    id: 'booking-006',
    packageSlug: 'zermatt-alpine-escape',
    packageTitle: 'Zermatt Alpine Escape',
    packageImage: '/images/countries/switzerland/switzerland-2.webp',
    packageLocation: 'Zermatt, Switzerland',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2025-10-09',
    bookingRef: 'TRV-0024-QMNU',
    totalAmount: 2099,
    paymentResult: { method: 'card', cardLast4: '8628' },
    bookedAt: '2025-09-11T17:03:00.000Z',
    status: 'completed',
    contactName: 'Amelia Carter',
    contactEmail: 'amelia.carter@example.com',
    contactPhone: '+1 415-552-1187',
    contactAvatar: '/images/avatars/avatar-2.webp',
    baseAmount: 2099
  },
  {
    id: 'booking-007',
    packageSlug: 'geneva-lakeside-discovery',
    packageTitle: 'Geneva Lakeside Discovery',
    packageImage: '/images/countries/switzerland/switzerland-3.webp',
    packageLocation: 'Geneva, Switzerland',
    packageDays: 4,
    packageNights: 3,
    travelers: 2,
    travelDate: '2026-03-11',
    bookingRef: 'TRV-0025-FPNX',
    totalAmount: 3598,
    paymentResult: { method: 'card', cardLast4: '8353' },
    bookedAt: '2026-01-27T19:49:00.000Z',
    status: 'completed',
    contactName: 'Amelia Carter',
    contactEmail: 'amelia.carter@example.com',
    contactPhone: '+1 415-552-1187',
    contactAvatar: '/images/avatars/avatar-2.webp',
    baseAmount: 3598
  },
  {
    id: 'booking-008',
    packageSlug: 'taj-mahal-trail',
    packageTitle: 'Taj Mahal',
    packageImage: '/images/countries/india/india-1.webp',
    packageLocation: 'Agra, India',
    packageDays: 8,
    packageNights: 7,
    travelers: 1,
    travelDate: '2026-09-21',
    bookingRef: 'TRV-0026-DMAS',
    totalAmount: 1149,
    paymentResult: { method: 'card', cardLast4: '6140' },
    bookedAt: '2026-09-01T20:21:00.000Z',
    status: 'cancelled',
    contactName: 'Amelia Carter',
    contactEmail: 'amelia.carter@example.com',
    contactPhone: '+1 415-552-1187',
    contactAvatar: '/images/avatars/avatar-2.webp',
    baseAmount: 1149
  },
  {
    id: 'booking-009',
    packageSlug: 'kerala-backwaters-bliss',
    packageTitle: 'Kerala Backwaters Bliss',
    packageImage: '/images/countries/india/india-2.webp',
    packageLocation: 'Kerala, India',
    packageDays: 6,
    packageNights: 5,
    travelers: 3,
    travelDate: '2025-11-25',
    bookingRef: 'TRV-0031-MRBS',
    totalAmount: 3897,
    paymentResult: { method: 'card', cardLast4: '8301' },
    bookedAt: '2025-10-28T09:17:00.000Z',
    status: 'completed',
    contactName: 'Noah Williams',
    contactEmail: 'noah.williams@example.com',
    contactPhone: '+1 312-664-2098',
    contactAvatar: '/images/avatars/avatar-3.webp',
    baseAmount: 3897
  },
  {
    id: 'booking-010',
    packageSlug: 'maldives-honeymoon-bliss',
    packageTitle: 'Maldives Honeymoon Bliss',
    packageImage: '/images/countries/maldives/maldives-1.webp',
    packageLocation: 'Malé Atoll, Maldives',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-11-16',
    bookingRef: 'TRV-0032-ECBU',
    totalAmount: 6598,
    paymentResult: { method: 'card', cardLast4: '3119' },
    bookedAt: '2026-08-02T15:22:00.000Z',
    status: 'upcoming',
    contactName: 'Noah Williams',
    contactEmail: 'noah.williams@example.com',
    contactPhone: '+1 312-664-2098',
    contactAvatar: '/images/avatars/avatar-3.webp',
    baseAmount: 6598
  },
  {
    id: 'booking-011',
    packageSlug: 'maldives-scuba-snorkel-adventure',
    packageTitle: 'Maldives Scuba & Snorkel Adventure',
    packageImage: '/images/countries/maldives/maldives-2.webp',
    packageLocation: 'Baa Atoll, Maldives',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2025-11-04',
    bookingRef: 'TRV-0033-KGDL',
    totalAmount: 5798,
    paymentResult: { method: 'card', cardLast4: '5561' },
    bookedAt: '2025-10-05T10:28:00.000Z',
    status: 'completed',
    contactName: 'Noah Williams',
    contactEmail: 'noah.williams@example.com',
    contactPhone: '+1 312-664-2098',
    contactAvatar: '/images/avatars/avatar-3.webp',
    baseAmount: 5798
  },
  {
    id: 'booking-012',
    packageSlug: 'kenya-safari-explorer',
    packageTitle: 'Kenya Safari Explorer',
    packageImage: '/images/countries/kenya/kenya-1.webp',
    packageLocation: 'Maasai Mara, Kenya',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-11-25',
    bookingRef: 'TRV-0034-EFFM',
    totalAmount: 5098,
    paymentResult: { method: 'card', cardLast4: '3987' },
    bookedAt: '2026-07-20T10:05:00.000Z',
    status: 'upcoming',
    contactName: 'Noah Williams',
    contactEmail: 'noah.williams@example.com',
    contactPhone: '+1 312-664-2098',
    contactAvatar: '/images/avatars/avatar-3.webp',
    baseAmount: 5098
  },
  {
    id: 'booking-013',
    packageSlug: 'amboseli-elephant-safari',
    packageTitle: 'Amboseli Elephant Safari',
    packageImage: '/images/countries/kenya/kenya-2.webp',
    packageLocation: 'Amboseli, Kenya',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-10-20',
    bookingRef: 'TRV-0035-HDWY',
    totalAmount: 2199,
    paymentResult: { method: 'card', cardLast4: '1884' },
    bookedAt: '2026-09-17T17:36:00.000Z',
    status: 'cancelled',
    contactName: 'Noah Williams',
    contactEmail: 'noah.williams@example.com',
    contactPhone: '+1 312-664-2098',
    contactAvatar: '/images/avatars/avatar-3.webp',
    baseAmount: 2199
  },
  {
    id: 'booking-014',
    packageSlug: 'santorini-sunset-getaway',
    packageTitle: 'Santorini Sunset Getaway',
    packageImage: '/images/countries/greece/greece-1.webp',
    packageLocation: 'Santorini, Greece',
    packageDays: 6,
    packageNights: 5,
    travelers: 3,
    travelDate: '2025-12-24',
    bookingRef: 'TRV-0036-RBBF',
    totalAmount: 8097,
    paymentResult: { method: 'card', cardLast4: '3659' },
    bookedAt: '2025-10-15T09:30:00.000Z',
    status: 'completed',
    contactName: 'Noah Williams',
    contactEmail: 'noah.williams@example.com',
    contactPhone: '+1 312-664-2098',
    contactAvatar: '/images/avatars/avatar-3.webp',
    baseAmount: 8097
  },
  {
    id: 'booking-015',
    packageSlug: 'athens-ancient-wonders',
    packageTitle: 'Athens Ancient Wonders',
    packageImage: '/images/countries/greece/greece-2.webp',
    packageLocation: 'Athens, Greece',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-07-14',
    bookingRef: 'TRV-0041-QBEK',
    totalAmount: 1599,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-05-31T09:23:00.000Z',
    status: 'cancelled',
    contactName: 'Sophia Martinez',
    contactEmail: 'sophia.martinez@example.com',
    contactPhone: '+1 213-778-4432',
    contactAvatar: '/images/avatars/avatar-4.webp',
    baseAmount: 1599
  },
  {
    id: 'booking-016',
    packageSlug: 'queenstown-adrenaline-rush',
    packageTitle: 'Queenstown Adrenaline Rush',
    packageImage: '/images/countries/newzealand/newzealand-1.webp',
    packageLocation: 'Queenstown, New Zealand',
    packageDays: 7,
    packageNights: 6,
    travelers: 3,
    travelDate: '2026-05-15',
    bookingRef: 'TRV-0042-MHDT',
    totalAmount: 7197,
    paymentResult: { method: 'card', cardLast4: '5337' },
    bookedAt: '2026-04-11T15:29:00.000Z',
    status: 'completed',
    contactName: 'Sophia Martinez',
    contactEmail: 'sophia.martinez@example.com',
    contactPhone: '+1 213-778-4432',
    contactAvatar: '/images/avatars/avatar-4.webp',
    baseAmount: 7197
  },
  {
    id: 'booking-017',
    packageSlug: 'fiordland-wilderness-trail',
    packageTitle: 'Fiordland Wilderness Trail',
    packageImage: '/images/countries/newzealand/newzealand-2.webp',
    packageLocation: 'Fiordland, New Zealand',
    packageDays: 6,
    packageNights: 5,
    travelers: 3,
    travelDate: '2026-10-19',
    bookingRef: 'TRV-0051-PANZ',
    totalAmount: 6897,
    paymentResult: { method: 'card', cardLast4: '2491' },
    bookedAt: '2026-09-16T10:44:00.000Z',
    status: 'cancelled',
    contactName: 'Liam Anderson',
    contactEmail: 'liam.anderson@example.com',
    contactPhone: '+1 646-221-9075',
    contactAvatar: '/images/avatars/avatar-5.webp',
    baseAmount: 6897
  },
  {
    id: 'booking-018',
    packageSlug: 'kyoto-temple-discovery',
    packageTitle: 'Kyoto Temple Discovery',
    packageImage: '/images/countries/japan/japan-1.webp',
    packageLocation: 'Kyoto, Japan',
    packageDays: 8,
    packageNights: 7,
    travelers: 2,
    travelDate: '2026-04-22',
    bookingRef: 'TRV-0052-NUHF',
    totalAmount: 3798,
    paymentResult: { method: 'card', cardLast4: '4197' },
    bookedAt: '2026-02-16T20:14:00.000Z',
    status: 'completed',
    contactName: 'Liam Anderson',
    contactEmail: 'liam.anderson@example.com',
    contactPhone: '+1 646-221-9075',
    contactAvatar: '/images/avatars/avatar-5.webp',
    baseAmount: 3798
  },
  {
    id: 'booking-019',
    packageSlug: 'tokyo-neon-nights',
    packageTitle: 'Tokyo Neon Nights',
    packageImage: '/images/countries/japan/japan-2.webp',
    packageLocation: 'Tokyo, Japan',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-10-17',
    bookingRef: 'TRV-0053-JAAG',
    totalAmount: 4798,
    paymentResult: { method: 'card', cardLast4: '5246' },
    bookedAt: '2026-07-22T16:31:00.000Z',
    status: 'upcoming',
    contactName: 'Liam Anderson',
    contactEmail: 'liam.anderson@example.com',
    contactPhone: '+1 646-221-9075',
    contactAvatar: '/images/avatars/avatar-5.webp',
    baseAmount: 4798
  },
  {
    id: 'booking-020',
    packageSlug: 'osaka-street-food-trail',
    packageTitle: 'Osaka Street Food Trail',
    packageImage: '/images/countries/japan/japan-3.webp',
    packageLocation: 'Osaka, Japan',
    packageDays: 5,
    packageNights: 4,
    travelers: 3,
    travelDate: '2026-12-12',
    bookingRef: 'TRV-0054-FFEE',
    totalAmount: 5097,
    paymentResult: { method: 'card', cardLast4: '1031' },
    bookedAt: '2026-07-12T13:05:00.000Z',
    status: 'upcoming',
    contactName: 'Liam Anderson',
    contactEmail: 'liam.anderson@example.com',
    contactPhone: '+1 646-221-9075',
    contactAvatar: '/images/avatars/avatar-5.webp',
    baseAmount: 5097
  },
  {
    id: 'booking-021',
    packageSlug: 'dubai-luxury-city-break',
    packageTitle: 'Dubai Luxury City Break',
    packageImage: '/images/countries/uae/uae-1.webp',
    packageLocation: 'Dubai, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 1,
    travelDate: '2026-09-19',
    bookingRef: 'TRV-0061-UMEU',
    totalAmount: 1999,
    paymentResult: { method: 'card', cardLast4: '6447' },
    bookedAt: '2026-07-10T20:45:00.000Z',
    status: 'upcoming',
    contactName: 'Olivia Brown',
    contactEmail: 'olivia.brown@example.com',
    contactPhone: '+1 702-330-5561',
    contactAvatar: '/images/avatars/avatar-6.webp',
    baseAmount: 1999
  },
  {
    id: 'booking-022',
    packageSlug: 'abu-dhabi-desert-safari',
    packageTitle: 'Abu Dhabi Desert Safari',
    packageImage: '/images/countries/uae/uae-2.webp',
    packageLocation: 'Abu Dhabi, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 2,
    travelDate: '2026-06-03',
    bookingRef: 'TRV-0062-AQMR',
    totalAmount: 3198,
    paymentResult: { method: 'card', cardLast4: '8771' },
    bookedAt: '2026-04-24T10:08:00.000Z',
    status: 'completed',
    contactName: 'Olivia Brown',
    contactEmail: 'olivia.brown@example.com',
    contactPhone: '+1 702-330-5561',
    contactAvatar: '/images/avatars/avatar-6.webp',
    baseAmount: 3198
  },
  {
    id: 'booking-023',
    packageSlug: 'dubai-marina-cruise-and-skyline',
    packageTitle: 'Dubai Marina Cruise & Skyline',
    packageImage: '/images/countries/uae/uae-3.webp',
    packageLocation: 'Dubai Marina, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 2,
    travelDate: '2025-10-09',
    bookingRef: 'TRV-0063-VTCT',
    totalAmount: 4598,
    paymentResult: { method: 'card', cardLast4: '3281' },
    bookedAt: '2025-09-03T08:00:00.000Z',
    status: 'completed',
    contactName: 'Olivia Brown',
    contactEmail: 'olivia.brown@example.com',
    contactPhone: '+1 702-330-5561',
    contactAvatar: '/images/avatars/avatar-6.webp',
    baseAmount: 4598
  },
  {
    id: 'booking-024',
    packageSlug: 'sharjah-heritage-walk',
    packageTitle: 'Sharjah Heritage Walk',
    packageImage: '/images/countries/uae/uae-4.webp',
    packageLocation: 'Sharjah, UAE',
    packageDays: 3,
    packageNights: 2,
    travelers: 1,
    travelDate: '2026-10-13',
    bookingRef: 'TRV-0064-HFQG',
    totalAmount: 999,
    paymentResult: { method: 'card', cardLast4: '7865' },
    bookedAt: '2026-08-02T12:13:00.000Z',
    status: 'upcoming',
    contactName: 'Olivia Brown',
    contactEmail: 'olivia.brown@example.com',
    contactPhone: '+1 702-330-5561',
    contactAvatar: '/images/avatars/avatar-6.webp',
    baseAmount: 999
  },
  {
    id: 'booking-025',
    packageSlug: 'patagonia-trekking-expedition',
    packageTitle: 'Patagonia Trekking Expedition',
    packageImage: '/images/countries/chile/chile-1.webp',
    packageLocation: 'Torres del Paine, Chile',
    packageDays: 9,
    packageNights: 8,
    travelers: 1,
    travelDate: '2026-11-18',
    bookingRef: 'TRV-0065-VNVX',
    totalAmount: 3199,
    paymentResult: { method: 'card', cardLast4: '3142' },
    bookedAt: '2026-07-05T18:37:00.000Z',
    status: 'upcoming',
    contactName: 'Olivia Brown',
    contactEmail: 'olivia.brown@example.com',
    contactPhone: '+1 702-330-5561',
    contactAvatar: '/images/avatars/avatar-6.webp',
    baseAmount: 3199
  },
  {
    id: 'booking-026',
    packageSlug: 'atacama-desert-stargazing',
    packageTitle: 'Atacama Desert Stargazing',
    packageImage: '/images/countries/chile/chile-2.webp',
    packageLocation: 'San Pedro de Atacama, Chile',
    packageDays: 5,
    packageNights: 4,
    travelers: 3,
    travelDate: '2025-12-03',
    bookingRef: 'TRV-0066-UDDQ',
    totalAmount: 7797,
    paymentResult: { method: 'card', cardLast4: '2971' },
    bookedAt: '2025-10-21T17:00:00.000Z',
    status: 'completed',
    contactName: 'Olivia Brown',
    contactEmail: 'olivia.brown@example.com',
    contactPhone: '+1 702-330-5561',
    contactAvatar: '/images/avatars/avatar-6.webp',
    baseAmount: 7797
  },
  {
    id: 'booking-027',
    packageSlug: 'phuket-beach-bliss',
    packageTitle: 'Phuket Beach Bliss',
    packageImage: '/images/countries/thailand/thailand-1.webp',
    packageLocation: 'Phuket, Thailand',
    packageDays: 6,
    packageNights: 5,
    travelers: 3,
    travelDate: '2025-11-11',
    bookingRef: 'TRV-0071-FGUN',
    totalAmount: 3297,
    paymentResult: { method: 'card', cardLast4: '1456' },
    bookedAt: '2025-10-09T16:03:00.000Z',
    status: 'completed',
    contactName: 'Ethan Davis',
    contactEmail: 'ethan.davis@example.com',
    contactPhone: '+1 917-440-6623',
    contactAvatar: '/images/avatars/avatar-7.webp',
    baseAmount: 3297
  },
  {
    id: 'booking-028',
    packageSlug: 'bangkok-grand-palace-tour',
    packageTitle: 'Bangkok Grand Palace Tour',
    packageImage: '/images/countries/thailand/thailand-2.webp',
    packageLocation: 'Bangkok, Thailand',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2025-10-31',
    bookingRef: 'TRV-0072-GNVN',
    totalAmount: 1099,
    paymentResult: { method: 'card', cardLast4: '5057' },
    bookedAt: '2025-08-07T11:44:00.000Z',
    status: 'completed',
    contactName: 'Ethan Davis',
    contactEmail: 'ethan.davis@example.com',
    contactPhone: '+1 917-440-6623',
    contactAvatar: '/images/avatars/avatar-7.webp',
    baseAmount: 1099
  },
  {
    id: 'booking-029',
    packageSlug: 'chiang-mai-jungle-retreat',
    packageTitle: 'Chiang Mai Jungle Retreat',
    packageImage: '/images/countries/thailand/thailand-3.webp',
    packageLocation: 'Chiang Mai, Thailand',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-10-10',
    bookingRef: 'TRV-0073-CLBF',
    totalAmount: 2498,
    paymentResult: { method: 'card', cardLast4: '2198' },
    bookedAt: '2026-07-06T10:26:00.000Z',
    status: 'upcoming',
    contactName: 'Ethan Davis',
    contactEmail: 'ethan.davis@example.com',
    contactPhone: '+1 917-440-6623',
    contactAvatar: '/images/avatars/avatar-7.webp',
    baseAmount: 2498
  },
  {
    id: 'booking-030',
    packageSlug: 'banff-wildlife-and-rockies-trail',
    packageTitle: 'Banff Wildlife & Rockies Trail',
    packageImage: '/images/countries/canada/canada-1.webp',
    packageLocation: 'Banff, Canada',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2027-03-06',
    bookingRef: 'TRV-0074-RDXZ',
    totalAmount: 4598,
    paymentResult: { method: 'card', cardLast4: '4597' },
    bookedAt: '2026-07-25T19:41:00.000Z',
    status: 'upcoming',
    contactName: 'Ethan Davis',
    contactEmail: 'ethan.davis@example.com',
    contactPhone: '+1 917-440-6623',
    contactAvatar: '/images/avatars/avatar-7.webp',
    baseAmount: 4598
  },
  {
    id: 'booking-031',
    packageSlug: 'niagara-falls-getaway',
    packageTitle: 'Niagara Falls Getaway',
    packageImage: '/images/countries/canada/canada-2.webp',
    packageLocation: 'Niagara Falls, Canada',
    packageDays: 3,
    packageNights: 2,
    travelers: 1,
    travelDate: '2025-11-09',
    bookingRef: 'TRV-0075-FSZK',
    totalAmount: 899,
    paymentResult: { method: 'card', cardLast4: '7902' },
    bookedAt: '2025-09-30T18:53:00.000Z',
    status: 'completed',
    contactName: 'Ethan Davis',
    contactEmail: 'ethan.davis@example.com',
    contactPhone: '+1 917-440-6623',
    contactAvatar: '/images/avatars/avatar-7.webp',
    baseAmount: 899
  },
  {
    id: 'booking-032',
    packageSlug: 'great-barrier-reef-discovery',
    packageTitle: 'Great Barrier Reef Discovery',
    packageImage: '/images/countries/australia/australia-1.webp',
    packageLocation: 'Cairns, Australia',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-09-07',
    bookingRef: 'TRV-0076-MSKN',
    totalAmount: 5598,
    paymentResult: { method: 'card', cardLast4: '5840' },
    bookedAt: '2026-08-27T13:35:00.000Z',
    status: 'cancelled',
    contactName: 'Ethan Davis',
    contactEmail: 'ethan.davis@example.com',
    contactPhone: '+1 917-440-6623',
    contactAvatar: '/images/avatars/avatar-7.webp',
    baseAmount: 5598
  },
  {
    id: 'booking-033',
    packageSlug: 'sydney-harbour-explorer',
    packageTitle: 'Sydney Harbour Explorer',
    packageImage: '/images/countries/australia/australia-2.webp',
    packageLocation: 'Sydney, Australia',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2027-03-09',
    bookingRef: 'TRV-0081-GAUG',
    totalAmount: 1899,
    paymentResult: { method: 'card', cardLast4: '3122' },
    bookedAt: '2026-07-20T09:05:00.000Z',
    status: 'upcoming',
    contactName: 'Isabella Wilson',
    contactEmail: 'isabella.wilson@example.com',
    contactPhone: '+1 305-889-7712',
    contactAvatar: '/images/avatars/avatar-8.webp',
    baseAmount: 1899
  },
  {
    id: 'booking-034',
    packageSlug: 'moscow-kremlin-and-red-square',
    packageTitle: 'Moscow Kremlin & Red Square',
    packageImage: '/images/countries/russia/russia-1.webp',
    packageLocation: 'Moscow, Russia',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2025-10-15',
    bookingRef: 'TRV-0082-SCBS',
    totalAmount: 3598,
    paymentResult: { method: 'upi' },
    bookedAt: '2025-07-22T17:31:00.000Z',
    status: 'completed',
    contactName: 'Isabella Wilson',
    contactEmail: 'isabella.wilson@example.com',
    contactPhone: '+1 305-889-7712',
    contactAvatar: '/images/avatars/avatar-8.webp',
    baseAmount: 3598
  },
  {
    id: 'booking-035',
    packageSlug: 'saint-petersburg-palace-tour',
    packageTitle: 'Saint Petersburg Palace Tour',
    packageImage: '/images/countries/russia/russia-2.webp',
    packageLocation: 'Saint Petersburg, Russia',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2027-01-29',
    bookingRef: 'TRV-0083-CWBW',
    totalAmount: 3898,
    paymentResult: { method: 'card', cardLast4: '8434' },
    bookedAt: '2026-07-29T20:16:00.000Z',
    status: 'upcoming',
    contactName: 'Isabella Wilson',
    contactEmail: 'isabella.wilson@example.com',
    contactPhone: '+1 305-889-7712',
    contactAvatar: '/images/avatars/avatar-8.webp',
    baseAmount: 3898
  },
  {
    id: 'booking-036',
    packageSlug: 'new-york-city-explorer',
    packageTitle: 'New York City Explorer',
    packageImage: '/images/countries/usa/usa-1.webp',
    packageLocation: 'New York City, USA',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-10-27',
    bookingRef: 'TRV-0091-NFCD',
    totalAmount: 4398,
    paymentResult: { method: 'card', cardLast4: '1825' },
    bookedAt: '2026-06-25T10:02:00.000Z',
    status: 'upcoming',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 4398
  },
  {
    id: 'booking-037',
    packageSlug: 'grand-canyon-adventure',
    packageTitle: 'Grand Canyon Adventure',
    packageImage: '/images/countries/usa/usa-2.webp',
    packageLocation: 'Grand Canyon, Arizona, USA',
    packageDays: 4,
    packageNights: 3,
    travelers: 2,
    travelDate: '2027-01-02',
    bookingRef: 'TRV-0092-NEJA',
    totalAmount: 3398,
    paymentResult: { method: 'card', cardLast4: '5103' },
    bookedAt: '2026-07-21T12:28:00.000Z',
    status: 'upcoming',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 3398
  },
  {
    id: 'booking-038',
    packageSlug: 'bali-island-escape',
    packageTitle: 'Bali Island Escape',
    packageImage: '/images/countries/indonesia/indonesia-1.webp',
    packageLocation: 'Bali, Indonesia',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2027-01-08',
    bookingRef: 'TRV-0093-FLRR',
    totalAmount: 899,
    paymentResult: { method: 'card', cardLast4: '9110' },
    bookedAt: '2026-07-22T16:30:00.000Z',
    status: 'upcoming',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 899
  },
  {
    id: 'booking-039',
    packageSlug: 'ubud-rice-terrace-retreat',
    packageTitle: 'Ubud Rice Terrace Retreat',
    packageImage: '/images/countries/indonesia/indonesia-2.webp',
    packageLocation: 'Ubud, Indonesia',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-11-06',
    bookingRef: 'TRV-0094-EXTD',
    totalAmount: 1498,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-07-21T11:21:00.000Z',
    status: 'upcoming',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 1498
  },
  {
    id: 'booking-040',
    packageSlug: 'swiss-alps-adventure',
    packageTitle: 'Swiss Alps Adventure',
    packageImage: '/images/countries/switzerland/switzerland-1.webp',
    packageLocation: 'Interlaken, Switzerland',
    packageDays: 7,
    packageNights: 6,
    travelers: 1,
    travelDate: '2026-11-13',
    bookingRef: 'TRV-0095-DCWW',
    totalAmount: 2199,
    paymentResult: { method: 'card', cardLast4: '5619' },
    bookedAt: '2026-09-17T12:27:00.000Z',
    status: 'cancelled',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 2199
  },
  {
    id: 'booking-041',
    packageSlug: 'zermatt-alpine-escape',
    packageTitle: 'Zermatt Alpine Escape',
    packageImage: '/images/countries/switzerland/switzerland-2.webp',
    packageLocation: 'Zermatt, Switzerland',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-07-23',
    bookingRef: 'TRV-0096-AJHZ',
    totalAmount: 4198,
    paymentResult: { method: 'card', cardLast4: '6300' },
    bookedAt: '2026-07-03T12:28:00.000Z',
    status: 'cancelled',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 4198
  },
  {
    id: 'booking-042',
    packageSlug: 'geneva-lakeside-discovery',
    packageTitle: 'Geneva Lakeside Discovery',
    packageImage: '/images/countries/switzerland/switzerland-3.webp',
    packageLocation: 'Geneva, Switzerland',
    packageDays: 4,
    packageNights: 3,
    travelers: 2,
    travelDate: '2026-04-14',
    bookingRef: 'TRV-0097-CGRF',
    totalAmount: 3598,
    paymentResult: { method: 'card', cardLast4: '1081' },
    bookedAt: '2026-03-25T13:24:00.000Z',
    status: 'completed',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 3598
  },
  {
    id: 'booking-043',
    packageSlug: 'taj-mahal-trail',
    packageTitle: 'Taj Mahal',
    packageImage: '/images/countries/india/india-1.webp',
    packageLocation: 'Agra, India',
    packageDays: 8,
    packageNights: 7,
    travelers: 1,
    travelDate: '2026-11-03',
    bookingRef: 'TRV-0098-HRCY',
    totalAmount: 1149,
    paymentResult: { method: 'card', cardLast4: '3543' },
    bookedAt: '2026-10-22T14:01:00.000Z',
    status: 'cancelled',
    contactName: 'James Taylor',
    contactEmail: 'james.taylor@example.com',
    contactPhone: '+1 480-556-3390',
    contactAvatar: '/images/avatars/avatar-9.webp',
    baseAmount: 1149
  },
  {
    id: 'booking-044',
    packageSlug: 'kerala-backwaters-bliss',
    packageTitle: 'Kerala Backwaters Bliss',
    packageImage: '/images/countries/india/india-2.webp',
    packageLocation: 'Kerala, India',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-12-24',
    bookingRef: 'TRV-0101-QDVT',
    totalAmount: 2598,
    paymentResult: { method: 'card', cardLast4: '9404' },
    bookedAt: '2026-07-25T12:46:00.000Z',
    status: 'upcoming',
    contactName: 'Charlotte Moore',
    contactEmail: 'charlotte.moore@example.com',
    contactPhone: '+1 720-994-2287',
    contactAvatar: '/images/avatars/avatar-10.webp',
    baseAmount: 2598
  },
  {
    id: 'booking-045',
    packageSlug: 'maldives-honeymoon-bliss',
    packageTitle: 'Maldives Honeymoon Bliss',
    packageImage: '/images/countries/maldives/maldives-1.webp',
    packageLocation: 'Malé Atoll, Maldives',
    packageDays: 5,
    packageNights: 4,
    travelers: 3,
    travelDate: '2026-10-18',
    bookingRef: 'TRV-0102-WVVQ',
    totalAmount: 9897,
    paymentResult: { method: 'card', cardLast4: '4767' },
    bookedAt: '2026-08-21T16:36:00.000Z',
    status: 'cancelled',
    contactName: 'Charlotte Moore',
    contactEmail: 'charlotte.moore@example.com',
    contactPhone: '+1 720-994-2287',
    contactAvatar: '/images/avatars/avatar-10.webp',
    baseAmount: 9897
  },
  {
    id: 'booking-046',
    packageSlug: 'maldives-scuba-snorkel-adventure',
    packageTitle: 'Maldives Scuba & Snorkel Adventure',
    packageImage: '/images/countries/maldives/maldives-2.webp',
    packageLocation: 'Baa Atoll, Maldives',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-09-06',
    bookingRef: 'TRV-0103-LBAN',
    totalAmount: 2899,
    paymentResult: { method: 'card', cardLast4: '5006' },
    bookedAt: '2026-08-21T14:53:00.000Z',
    status: 'cancelled',
    contactName: 'Charlotte Moore',
    contactEmail: 'charlotte.moore@example.com',
    contactPhone: '+1 720-994-2287',
    contactAvatar: '/images/avatars/avatar-10.webp',
    baseAmount: 2899
  },
  {
    id: 'booking-047',
    packageSlug: 'kenya-safari-explorer',
    packageTitle: 'Kenya Safari Explorer',
    packageImage: '/images/countries/kenya/kenya-1.webp',
    packageLocation: 'Maasai Mara, Kenya',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2026-06-11',
    bookingRef: 'TRV-0104-RBTG',
    totalAmount: 2549,
    paymentResult: { method: 'card', cardLast4: '2219' },
    bookedAt: '2026-03-19T16:05:00.000Z',
    status: 'completed',
    contactName: 'Charlotte Moore',
    contactEmail: 'charlotte.moore@example.com',
    contactPhone: '+1 720-994-2287',
    contactAvatar: '/images/avatars/avatar-10.webp',
    baseAmount: 2549
  },
  {
    id: 'booking-048',
    packageSlug: 'amboseli-elephant-safari',
    packageTitle: 'Amboseli Elephant Safari',
    packageImage: '/images/countries/kenya/kenya-2.webp',
    packageLocation: 'Amboseli, Kenya',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-10-11',
    bookingRef: 'TRV-0105-ZMKM',
    totalAmount: 2199,
    paymentResult: { method: 'card', cardLast4: '5707' },
    bookedAt: '2026-07-20T19:41:00.000Z',
    status: 'upcoming',
    contactName: 'Charlotte Moore',
    contactEmail: 'charlotte.moore@example.com',
    contactPhone: '+1 720-994-2287',
    contactAvatar: '/images/avatars/avatar-10.webp',
    baseAmount: 2199
  },
  {
    id: 'booking-049',
    packageSlug: 'santorini-sunset-getaway',
    packageTitle: 'Santorini Sunset Getaway',
    packageImage: '/images/countries/greece/greece-1.webp',
    packageLocation: 'Santorini, Greece',
    packageDays: 6,
    packageNights: 5,
    travelers: 3,
    travelDate: '2026-10-09',
    bookingRef: 'TRV-0106-HRSQ',
    totalAmount: 8097,
    paymentResult: { method: 'card', cardLast4: '3186' },
    bookedAt: '2026-07-30T17:09:00.000Z',
    status: 'upcoming',
    contactName: 'Charlotte Moore',
    contactEmail: 'charlotte.moore@example.com',
    contactPhone: '+1 720-994-2287',
    contactAvatar: '/images/avatars/avatar-10.webp',
    baseAmount: 8097
  },
  {
    id: 'booking-050',
    packageSlug: 'athens-ancient-wonders',
    packageTitle: 'Athens Ancient Wonders',
    packageImage: '/images/countries/greece/greece-2.webp',
    packageLocation: 'Athens, Greece',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-05-27',
    bookingRef: 'TRV-0111-GNMM',
    totalAmount: 3198,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-04-10T18:31:00.000Z',
    status: 'completed',
    contactName: 'Benjamin Clark',
    contactEmail: 'benjamin.clark@example.com',
    contactPhone: '+1 617-225-8834',
    contactAvatar: '/images/avatars/avatar-11.webp',
    baseAmount: 3198
  },
  {
    id: 'booking-051',
    packageSlug: 'queenstown-adrenaline-rush',
    packageTitle: 'Queenstown Adrenaline Rush',
    packageImage: '/images/countries/newzealand/newzealand-1.webp',
    packageLocation: 'Queenstown, New Zealand',
    packageDays: 7,
    packageNights: 6,
    travelers: 3,
    travelDate: '2026-06-03',
    bookingRef: 'TRV-0112-MVZL',
    totalAmount: 7197,
    paymentResult: { method: 'card', cardLast4: '5401' },
    bookedAt: '2026-03-15T08:18:00.000Z',
    status: 'completed',
    contactName: 'Benjamin Clark',
    contactEmail: 'benjamin.clark@example.com',
    contactPhone: '+1 617-225-8834',
    contactAvatar: '/images/avatars/avatar-11.webp',
    baseAmount: 7197
  },
  {
    id: 'booking-052',
    packageSlug: 'fiordland-wilderness-trail',
    packageTitle: 'Fiordland Wilderness Trail',
    packageImage: '/images/countries/newzealand/newzealand-2.webp',
    packageLocation: 'Fiordland, New Zealand',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2026-09-25',
    bookingRef: 'TRV-0121-DVNX',
    totalAmount: 2299,
    paymentResult: { method: 'card', cardLast4: '6983' },
    bookedAt: '2026-07-01T12:23:00.000Z',
    status: 'upcoming',
    contactName: 'Mia Rodriguez',
    contactEmail: 'mia.rodriguez@example.com',
    contactPhone: '+1 210-773-6612',
    contactAvatar: '/images/avatars/avatar-12.webp',
    baseAmount: 2299
  },
  {
    id: 'booking-053',
    packageSlug: 'kyoto-temple-discovery',
    packageTitle: 'Kyoto Temple Discovery',
    packageImage: '/images/countries/japan/japan-1.webp',
    packageLocation: 'Kyoto, Japan',
    packageDays: 8,
    packageNights: 7,
    travelers: 2,
    travelDate: '2026-04-26',
    bookingRef: 'TRV-0122-LHDJ',
    totalAmount: 3798,
    paymentResult: { method: 'card', cardLast4: '6178' },
    bookedAt: '2026-04-06T15:43:00.000Z',
    status: 'completed',
    contactName: 'Mia Rodriguez',
    contactEmail: 'mia.rodriguez@example.com',
    contactPhone: '+1 210-773-6612',
    contactAvatar: '/images/avatars/avatar-12.webp',
    baseAmount: 3798
  },
  {
    id: 'booking-054',
    packageSlug: 'tokyo-neon-nights',
    packageTitle: 'Tokyo Neon Nights',
    packageImage: '/images/countries/japan/japan-2.webp',
    packageLocation: 'Tokyo, Japan',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-08-31',
    bookingRef: 'TRV-0123-EATG',
    totalAmount: 4798,
    paymentResult: { method: 'card', cardLast4: '2064' },
    bookedAt: '2026-07-27T09:59:00.000Z',
    status: 'cancelled',
    contactName: 'Mia Rodriguez',
    contactEmail: 'mia.rodriguez@example.com',
    contactPhone: '+1 210-773-6612',
    contactAvatar: '/images/avatars/avatar-12.webp',
    baseAmount: 4798
  },
  {
    id: 'booking-055',
    packageSlug: 'osaka-street-food-trail',
    packageTitle: 'Osaka Street Food Trail',
    packageImage: '/images/countries/japan/japan-3.webp',
    packageLocation: 'Osaka, Japan',
    packageDays: 5,
    packageNights: 4,
    travelers: 3,
    travelDate: '2026-09-23',
    bookingRef: 'TRV-0124-BCWG',
    totalAmount: 5097,
    paymentResult: { method: 'card', cardLast4: '3439' },
    bookedAt: '2026-07-27T12:54:00.000Z',
    status: 'cancelled',
    contactName: 'Mia Rodriguez',
    contactEmail: 'mia.rodriguez@example.com',
    contactPhone: '+1 210-773-6612',
    contactAvatar: '/images/avatars/avatar-12.webp',
    baseAmount: 5097
  },
  {
    id: 'booking-056',
    packageSlug: 'dubai-luxury-city-break',
    packageTitle: 'Dubai Luxury City Break',
    packageImage: '/images/countries/uae/uae-1.webp',
    packageLocation: 'Dubai, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 2,
    travelDate: '2026-02-05',
    bookingRef: 'TRV-0125-ULAU',
    totalAmount: 3998,
    paymentResult: { method: 'upi' },
    bookedAt: '2025-12-23T20:23:00.000Z',
    status: 'completed',
    contactName: 'Mia Rodriguez',
    contactEmail: 'mia.rodriguez@example.com',
    contactPhone: '+1 210-773-6612',
    contactAvatar: '/images/avatars/avatar-12.webp',
    baseAmount: 3998
  },
  {
    id: 'booking-057',
    packageSlug: 'abu-dhabi-desert-safari',
    packageTitle: 'Abu Dhabi Desert Safari',
    packageImage: '/images/countries/uae/uae-2.webp',
    packageLocation: 'Abu Dhabi, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 3,
    travelDate: '2026-06-05',
    bookingRef: 'TRV-0131-LURG',
    totalAmount: 4797,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-05-10T19:26:00.000Z',
    status: 'completed',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 4797
  },
  {
    id: 'booking-058',
    packageSlug: 'dubai-marina-cruise-and-skyline',
    packageTitle: 'Dubai Marina Cruise & Skyline',
    packageImage: '/images/countries/uae/uae-3.webp',
    packageLocation: 'Dubai Marina, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 3,
    travelDate: '2026-10-04',
    bookingRef: 'TRV-0132-HTZG',
    totalAmount: 6897,
    paymentResult: { method: 'card', cardLast4: '4910' },
    bookedAt: '2026-08-29T13:18:00.000Z',
    status: 'cancelled',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 6897
  },
  {
    id: 'booking-059',
    packageSlug: 'sharjah-heritage-walk',
    packageTitle: 'Sharjah Heritage Walk',
    packageImage: '/images/countries/uae/uae-4.webp',
    packageLocation: 'Sharjah, UAE',
    packageDays: 3,
    packageNights: 2,
    travelers: 3,
    travelDate: '2026-09-19',
    bookingRef: 'TRV-0133-BNVP',
    totalAmount: 2997,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-07-24T18:10:00.000Z',
    status: 'upcoming',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 2997
  },
  {
    id: 'booking-060',
    packageSlug: 'patagonia-trekking-expedition',
    packageTitle: 'Patagonia Trekking Expedition',
    packageImage: '/images/countries/chile/chile-1.webp',
    packageLocation: 'Torres del Paine, Chile',
    packageDays: 9,
    packageNights: 8,
    travelers: 2,
    travelDate: '2025-10-09',
    bookingRef: 'TRV-0134-EPHJ',
    totalAmount: 6398,
    paymentResult: { method: 'upi' },
    bookedAt: '2025-08-26T11:05:00.000Z',
    status: 'completed',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 6398
  },
  {
    id: 'booking-061',
    packageSlug: 'atacama-desert-stargazing',
    packageTitle: 'Atacama Desert Stargazing',
    packageImage: '/images/countries/chile/chile-2.webp',
    packageLocation: 'San Pedro de Atacama, Chile',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2025-10-21',
    bookingRef: 'TRV-0135-JBGZ',
    totalAmount: 5198,
    paymentResult: { method: 'card', cardLast4: '3062' },
    bookedAt: '2025-09-05T14:17:00.000Z',
    status: 'completed',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 5198
  },
  {
    id: 'booking-062',
    packageSlug: 'phuket-beach-bliss',
    packageTitle: 'Phuket Beach Bliss',
    packageImage: '/images/countries/thailand/thailand-1.webp',
    packageLocation: 'Phuket, Thailand',
    packageDays: 6,
    packageNights: 5,
    travelers: 3,
    travelDate: '2027-03-28',
    bookingRef: 'TRV-0136-XKRL',
    totalAmount: 3297,
    paymentResult: { method: 'card', cardLast4: '6112' },
    bookedAt: '2026-07-21T09:17:00.000Z',
    status: 'upcoming',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 3297
  },
  {
    id: 'booking-063',
    packageSlug: 'bangkok-grand-palace-tour',
    packageTitle: 'Bangkok Grand Palace Tour',
    packageImage: '/images/countries/thailand/thailand-2.webp',
    packageLocation: 'Bangkok, Thailand',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-09-22',
    bookingRef: 'TRV-0137-VZMB',
    totalAmount: 1099,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-07-29T20:57:00.000Z',
    status: 'cancelled',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 1099
  },
  {
    id: 'booking-064',
    packageSlug: 'chiang-mai-jungle-retreat',
    packageTitle: 'Chiang Mai Jungle Retreat',
    packageImage: '/images/countries/thailand/thailand-3.webp',
    packageLocation: 'Chiang Mai, Thailand',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-05-22',
    bookingRef: 'TRV-0138-NSYT',
    totalAmount: 2498,
    paymentResult: { method: 'card', cardLast4: '8492' },
    bookedAt: '2026-04-04T10:09:00.000Z',
    status: 'completed',
    contactName: 'Lucas Lewis',
    contactEmail: 'lucas.lewis@example.com',
    contactPhone: '+1 813-994-2201',
    contactAvatar: '/images/avatars/avatar-13.webp',
    baseAmount: 2498
  },
  {
    id: 'booking-065',
    packageSlug: 'banff-wildlife-and-rockies-trail',
    packageTitle: 'Banff Wildlife & Rockies Trail',
    packageImage: '/images/countries/canada/canada-1.webp',
    packageLocation: 'Banff, Canada',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2026-10-18',
    bookingRef: 'TRV-0141-TZRN',
    totalAmount: 2299,
    paymentResult: { method: 'card', cardLast4: '8166' },
    bookedAt: '2026-06-28T08:41:00.000Z',
    status: 'upcoming',
    contactName: 'Amelia Walker',
    contactEmail: 'amelia.walker@example.com',
    contactPhone: '+1 512-336-9087',
    contactAvatar: '/images/avatars/avatar-14.webp',
    baseAmount: 2299
  },
  {
    id: 'booking-066',
    packageSlug: 'niagara-falls-getaway',
    packageTitle: 'Niagara Falls Getaway',
    packageImage: '/images/countries/canada/canada-2.webp',
    packageLocation: 'Niagara Falls, Canada',
    packageDays: 3,
    packageNights: 2,
    travelers: 1,
    travelDate: '2026-08-21',
    bookingRef: 'TRV-0142-KFQA',
    totalAmount: 899,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-07-09T17:12:00.000Z',
    status: 'cancelled',
    contactName: 'Amelia Walker',
    contactEmail: 'amelia.walker@example.com',
    contactPhone: '+1 512-336-9087',
    contactAvatar: '/images/avatars/avatar-14.webp',
    baseAmount: 899
  },
  {
    id: 'booking-067',
    packageSlug: 'great-barrier-reef-discovery',
    packageTitle: 'Great Barrier Reef Discovery',
    packageImage: '/images/countries/australia/australia-1.webp',
    packageLocation: 'Cairns, Australia',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-10-21',
    bookingRef: 'TRV-0151-PAKR',
    totalAmount: 5598,
    paymentResult: { method: 'card', cardLast4: '1906' },
    bookedAt: '2026-07-04T16:15:00.000Z',
    status: 'upcoming',
    contactName: 'Henry Hall',
    contactEmail: 'henry.hall@example.com',
    contactPhone: '+1 619-448-7765',
    contactAvatar: '/images/avatars/avatar-15.webp',
    baseAmount: 5598
  },
  {
    id: 'booking-068',
    packageSlug: 'sydney-harbour-explorer',
    packageTitle: 'Sydney Harbour Explorer',
    packageImage: '/images/countries/australia/australia-2.webp',
    packageLocation: 'Sydney, Australia',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2027-02-01',
    bookingRef: 'TRV-0152-FLJM',
    totalAmount: 3798,
    paymentResult: { method: 'card', cardLast4: '6538' },
    bookedAt: '2026-07-08T09:16:00.000Z',
    status: 'upcoming',
    contactName: 'Henry Hall',
    contactEmail: 'henry.hall@example.com',
    contactPhone: '+1 619-448-7765',
    contactAvatar: '/images/avatars/avatar-15.webp',
    baseAmount: 3798
  },
  {
    id: 'booking-069',
    packageSlug: 'moscow-kremlin-and-red-square',
    packageTitle: 'Moscow Kremlin & Red Square',
    packageImage: '/images/countries/russia/russia-1.webp',
    packageLocation: 'Moscow, Russia',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-10-09',
    bookingRef: 'TRV-0153-TNEZ',
    totalAmount: 3598,
    paymentResult: { method: 'card', cardLast4: '6107' },
    bookedAt: '2026-08-03T20:18:00.000Z',
    status: 'upcoming',
    contactName: 'Henry Hall',
    contactEmail: 'henry.hall@example.com',
    contactPhone: '+1 619-448-7765',
    contactAvatar: '/images/avatars/avatar-15.webp',
    baseAmount: 3598
  },
  {
    id: 'booking-070',
    packageSlug: 'saint-petersburg-palace-tour',
    packageTitle: 'Saint Petersburg Palace Tour',
    packageImage: '/images/countries/russia/russia-2.webp',
    packageLocation: 'Saint Petersburg, Russia',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-03-25',
    bookingRef: 'TRV-0154-HYME',
    totalAmount: 1949,
    paymentResult: { method: 'card', cardLast4: '4658' },
    bookedAt: '2026-01-31T20:56:00.000Z',
    status: 'completed',
    contactName: 'Henry Hall',
    contactEmail: 'henry.hall@example.com',
    contactPhone: '+1 619-448-7765',
    contactAvatar: '/images/avatars/avatar-15.webp',
    baseAmount: 1949
  },
  {
    id: 'booking-071',
    packageSlug: 'new-york-city-explorer',
    packageTitle: 'New York City Explorer',
    packageImage: '/images/countries/usa/usa-1.webp',
    packageLocation: 'New York City, USA',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-09-26',
    bookingRef: 'TRV-0155-AQKT',
    totalAmount: 2199,
    paymentResult: { method: 'card', cardLast4: '4016' },
    bookedAt: '2026-07-09T08:13:00.000Z',
    status: 'upcoming',
    contactName: 'Henry Hall',
    contactEmail: 'henry.hall@example.com',
    contactPhone: '+1 619-448-7765',
    contactAvatar: '/images/avatars/avatar-15.webp',
    baseAmount: 2199
  },
  {
    id: 'booking-072',
    packageSlug: 'grand-canyon-adventure',
    packageTitle: 'Grand Canyon Adventure',
    packageImage: '/images/countries/usa/usa-2.webp',
    packageLocation: 'Grand Canyon, Arizona, USA',
    packageDays: 4,
    packageNights: 3,
    travelers: 1,
    travelDate: '2026-10-01',
    bookingRef: 'TRV-0161-RNMH',
    totalAmount: 1699,
    paymentResult: { method: 'card', cardLast4: '7203' },
    bookedAt: '2026-07-13T11:11:00.000Z',
    status: 'upcoming',
    contactName: 'Evelyn Allen',
    contactEmail: 'evelyn.allen@example.com',
    contactPhone: '+1 971-556-3320',
    contactAvatar: '/images/avatars/avatar-16.webp',
    baseAmount: 1699
  },
  {
    id: 'booking-073',
    packageSlug: 'bali-island-escape',
    packageTitle: 'Bali Island Escape',
    packageImage: '/images/countries/indonesia/indonesia-1.webp',
    packageLocation: 'Bali, Indonesia',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-05-22',
    bookingRef: 'TRV-0162-BLXP',
    totalAmount: 1798,
    paymentResult: { method: 'card', cardLast4: '4398' },
    bookedAt: '2026-05-02T09:17:00.000Z',
    status: 'completed',
    contactName: 'Evelyn Allen',
    contactEmail: 'evelyn.allen@example.com',
    contactPhone: '+1 971-556-3320',
    contactAvatar: '/images/avatars/avatar-16.webp',
    baseAmount: 1798
  },
  {
    id: 'booking-074',
    packageSlug: 'ubud-rice-terrace-retreat',
    packageTitle: 'Ubud Rice Terrace Retreat',
    packageImage: '/images/countries/indonesia/indonesia-2.webp',
    packageLocation: 'Ubud, Indonesia',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-12-08',
    bookingRef: 'TRV-0163-MJYE',
    totalAmount: 1498,
    paymentResult: { method: 'card', cardLast4: '6967' },
    bookedAt: '2026-07-29T08:45:00.000Z',
    status: 'upcoming',
    contactName: 'Evelyn Allen',
    contactEmail: 'evelyn.allen@example.com',
    contactPhone: '+1 971-556-3320',
    contactAvatar: '/images/avatars/avatar-16.webp',
    baseAmount: 1498
  },
  {
    id: 'booking-075',
    packageSlug: 'swiss-alps-adventure',
    packageTitle: 'Swiss Alps Adventure',
    packageImage: '/images/countries/switzerland/switzerland-1.webp',
    packageLocation: 'Interlaken, Switzerland',
    packageDays: 7,
    packageNights: 6,
    travelers: 2,
    travelDate: '2026-09-19',
    bookingRef: 'TRV-0164-UAAB',
    totalAmount: 4398,
    paymentResult: { method: 'card', cardLast4: '2015' },
    bookedAt: '2026-08-25T20:40:00.000Z',
    status: 'cancelled',
    contactName: 'Evelyn Allen',
    contactEmail: 'evelyn.allen@example.com',
    contactPhone: '+1 971-556-3320',
    contactAvatar: '/images/avatars/avatar-16.webp',
    baseAmount: 4398
  },
  {
    id: 'booking-076',
    packageSlug: 'zermatt-alpine-escape',
    packageTitle: 'Zermatt Alpine Escape',
    packageImage: '/images/countries/switzerland/switzerland-2.webp',
    packageLocation: 'Zermatt, Switzerland',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2026-11-14',
    bookingRef: 'TRV-0165-YQGT',
    totalAmount: 2099,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-07-11T12:21:00.000Z',
    status: 'upcoming',
    contactName: 'Evelyn Allen',
    contactEmail: 'evelyn.allen@example.com',
    contactPhone: '+1 971-556-3320',
    contactAvatar: '/images/avatars/avatar-16.webp',
    baseAmount: 2099
  },
  {
    id: 'booking-077',
    packageSlug: 'geneva-lakeside-discovery',
    packageTitle: 'Geneva Lakeside Discovery',
    packageImage: '/images/countries/switzerland/switzerland-3.webp',
    packageLocation: 'Geneva, Switzerland',
    packageDays: 4,
    packageNights: 3,
    travelers: 2,
    travelDate: '2026-11-05',
    bookingRef: 'TRV-0166-VCTM',
    totalAmount: 3598,
    paymentResult: { method: 'card', cardLast4: '7332' },
    bookedAt: '2026-09-16T09:01:00.000Z',
    status: 'cancelled',
    contactName: 'Evelyn Allen',
    contactEmail: 'evelyn.allen@example.com',
    contactPhone: '+1 971-556-3320',
    contactAvatar: '/images/avatars/avatar-16.webp',
    baseAmount: 3598
  },
  {
    id: 'booking-078',
    packageSlug: 'taj-mahal-trail',
    packageTitle: 'Taj Mahal',
    packageImage: '/images/countries/india/india-1.webp',
    packageLocation: 'Agra, India',
    packageDays: 8,
    packageNights: 7,
    travelers: 2,
    travelDate: '2026-10-11',
    bookingRef: 'TRV-0171-YHSD',
    totalAmount: 2298,
    paymentResult: { method: 'card', cardLast4: '4868' },
    bookedAt: '2026-09-20T08:51:00.000Z',
    status: 'cancelled',
    contactName: 'Alexander Young',
    contactEmail: 'alexander.young@example.com',
    contactPhone: '+1 404-887-2256',
    contactAvatar: '/images/avatars/avatar-17.webp',
    baseAmount: 2298
  },
  {
    id: 'booking-079',
    packageSlug: 'kerala-backwaters-bliss',
    packageTitle: 'Kerala Backwaters Bliss',
    packageImage: '/images/countries/india/india-2.webp',
    packageLocation: 'Kerala, India',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-06-06',
    bookingRef: 'TRV-0172-UFBA',
    totalAmount: 2598,
    paymentResult: { method: 'card', cardLast4: '9922' },
    bookedAt: '2026-03-13T11:25:00.000Z',
    status: 'completed',
    contactName: 'Alexander Young',
    contactEmail: 'alexander.young@example.com',
    contactPhone: '+1 404-887-2256',
    contactAvatar: '/images/avatars/avatar-17.webp',
    baseAmount: 2598
  },
  {
    id: 'booking-080',
    packageSlug: 'maldives-honeymoon-bliss',
    packageTitle: 'Maldives Honeymoon Bliss',
    packageImage: '/images/countries/maldives/maldives-1.webp',
    packageLocation: 'Malé Atoll, Maldives',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-09-07',
    bookingRef: 'TRV-0173-FLZZ',
    totalAmount: 6598,
    paymentResult: { method: 'card', cardLast4: '3837' },
    bookedAt: '2026-07-18T17:05:00.000Z',
    status: 'upcoming',
    contactName: 'Alexander Young',
    contactEmail: 'alexander.young@example.com',
    contactPhone: '+1 404-887-2256',
    contactAvatar: '/images/avatars/avatar-17.webp',
    baseAmount: 6598
  },
  {
    id: 'booking-081',
    packageSlug: 'maldives-scuba-snorkel-adventure',
    packageTitle: 'Maldives Scuba & Snorkel Adventure',
    packageImage: '/images/countries/maldives/maldives-2.webp',
    packageLocation: 'Baa Atoll, Maldives',
    packageDays: 5,
    packageNights: 4,
    travelers: 2,
    travelDate: '2026-03-18',
    bookingRef: 'TRV-0174-UUHG',
    totalAmount: 5798,
    paymentResult: { method: 'card', cardLast4: '5385' },
    bookedAt: '2025-12-20T20:42:00.000Z',
    status: 'completed',
    contactName: 'Alexander Young',
    contactEmail: 'alexander.young@example.com',
    contactPhone: '+1 404-887-2256',
    contactAvatar: '/images/avatars/avatar-17.webp',
    baseAmount: 5798
  },
  {
    id: 'booking-082',
    packageSlug: 'kenya-safari-explorer',
    packageTitle: 'Kenya Safari Explorer',
    packageImage: '/images/countries/kenya/kenya-1.webp',
    packageLocation: 'Maasai Mara, Kenya',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-03-12',
    bookingRef: 'TRV-0175-DXPH',
    totalAmount: 5098,
    paymentResult: { method: 'card', cardLast4: '7489' },
    bookedAt: '2026-01-28T11:15:00.000Z',
    status: 'completed',
    contactName: 'Alexander Young',
    contactEmail: 'alexander.young@example.com',
    contactPhone: '+1 404-887-2256',
    contactAvatar: '/images/avatars/avatar-17.webp',
    baseAmount: 5098
  },
  {
    id: 'booking-083',
    packageSlug: 'amboseli-elephant-safari',
    packageTitle: 'Amboseli Elephant Safari',
    packageImage: '/images/countries/kenya/kenya-2.webp',
    packageLocation: 'Amboseli, Kenya',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-03-20',
    bookingRef: 'TRV-0176-ZCMV',
    totalAmount: 2199,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-02-16T18:29:00.000Z',
    status: 'completed',
    contactName: 'Alexander Young',
    contactEmail: 'alexander.young@example.com',
    contactPhone: '+1 404-887-2256',
    contactAvatar: '/images/avatars/avatar-17.webp',
    baseAmount: 2199
  },
  {
    id: 'booking-084',
    packageSlug: 'santorini-sunset-getaway',
    packageTitle: 'Santorini Sunset Getaway',
    packageImage: '/images/countries/greece/greece-1.webp',
    packageLocation: 'Santorini, Greece',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-06-21',
    bookingRef: 'TRV-0181-PYJW',
    totalAmount: 5398,
    paymentResult: { method: 'card', cardLast4: '8358' },
    bookedAt: '2026-05-08T17:52:00.000Z',
    status: 'completed',
    contactName: 'Harper King',
    contactEmail: 'harper.king@example.com',
    contactPhone: '+1 206-771-4498',
    contactAvatar: '/images/avatars/avatar-18.webp',
    baseAmount: 5398
  },
  {
    id: 'booking-085',
    packageSlug: 'athens-ancient-wonders',
    packageTitle: 'Athens Ancient Wonders',
    packageImage: '/images/countries/greece/greece-2.webp',
    packageLocation: 'Athens, Greece',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2026-11-05',
    bookingRef: 'TRV-0182-FJDE',
    totalAmount: 1599,
    paymentResult: { method: 'card', cardLast4: '5176' },
    bookedAt: '2026-09-11T17:22:00.000Z',
    status: 'cancelled',
    contactName: 'Harper King',
    contactEmail: 'harper.king@example.com',
    contactPhone: '+1 206-771-4498',
    contactAvatar: '/images/avatars/avatar-18.webp',
    baseAmount: 1599
  },
  {
    id: 'booking-086',
    packageSlug: 'queenstown-adrenaline-rush',
    packageTitle: 'Queenstown Adrenaline Rush',
    packageImage: '/images/countries/newzealand/newzealand-1.webp',
    packageLocation: 'Queenstown, New Zealand',
    packageDays: 7,
    packageNights: 6,
    travelers: 1,
    travelDate: '2026-12-02',
    bookingRef: 'TRV-0191-QBAM',
    totalAmount: 2399,
    paymentResult: { method: 'card', cardLast4: '8921' },
    bookedAt: '2026-06-21T13:11:00.000Z',
    status: 'upcoming',
    contactName: 'Daniel Wright',
    contactEmail: 'daniel.wright@example.com',
    contactPhone: '+1 303-559-7743',
    contactAvatar: '/images/avatars/avatar-19.webp',
    baseAmount: 2399
  },
  {
    id: 'booking-087',
    packageSlug: 'fiordland-wilderness-trail',
    packageTitle: 'Fiordland Wilderness Trail',
    packageImage: '/images/countries/newzealand/newzealand-2.webp',
    packageLocation: 'Fiordland, New Zealand',
    packageDays: 6,
    packageNights: 5,
    travelers: 1,
    travelDate: '2027-02-05',
    bookingRef: 'TRV-0192-NRKG',
    totalAmount: 2299,
    paymentResult: { method: 'card', cardLast4: '5641' },
    bookedAt: '2026-06-29T10:40:00.000Z',
    status: 'upcoming',
    contactName: 'Daniel Wright',
    contactEmail: 'daniel.wright@example.com',
    contactPhone: '+1 303-559-7743',
    contactAvatar: '/images/avatars/avatar-19.webp',
    baseAmount: 2299
  },
  {
    id: 'booking-088',
    packageSlug: 'kyoto-temple-discovery',
    packageTitle: 'Kyoto Temple Discovery',
    packageImage: '/images/countries/japan/japan-1.webp',
    packageLocation: 'Kyoto, Japan',
    packageDays: 8,
    packageNights: 7,
    travelers: 2,
    travelDate: '2026-11-07',
    bookingRef: 'TRV-0193-KWZJ',
    totalAmount: 3798,
    paymentResult: { method: 'card', cardLast4: '4230' },
    bookedAt: '2026-06-28T13:26:00.000Z',
    status: 'upcoming',
    contactName: 'Daniel Wright',
    contactEmail: 'daniel.wright@example.com',
    contactPhone: '+1 303-559-7743',
    contactAvatar: '/images/avatars/avatar-19.webp',
    baseAmount: 3798
  },
  {
    id: 'booking-089',
    packageSlug: 'tokyo-neon-nights',
    packageTitle: 'Tokyo Neon Nights',
    packageImage: '/images/countries/japan/japan-2.webp',
    packageLocation: 'Tokyo, Japan',
    packageDays: 6,
    packageNights: 5,
    travelers: 2,
    travelDate: '2026-07-13',
    bookingRef: 'TRV-0194-CCPJ',
    totalAmount: 4798,
    paymentResult: { method: 'card', cardLast4: '3663' },
    bookedAt: '2026-04-29T10:27:00.000Z',
    status: 'completed',
    contactName: 'Daniel Wright',
    contactEmail: 'daniel.wright@example.com',
    contactPhone: '+1 303-559-7743',
    contactAvatar: '/images/avatars/avatar-19.webp',
    baseAmount: 4798
  },
  {
    id: 'booking-090',
    packageSlug: 'osaka-street-food-trail',
    packageTitle: 'Osaka Street Food Trail',
    packageImage: '/images/countries/japan/japan-3.webp',
    packageLocation: 'Osaka, Japan',
    packageDays: 5,
    packageNights: 4,
    travelers: 1,
    travelDate: '2027-01-31',
    bookingRef: 'TRV-0195-QJND',
    totalAmount: 1699,
    paymentResult: { method: 'card', cardLast4: '5641' },
    bookedAt: '2026-07-09T09:36:00.000Z',
    status: 'upcoming',
    contactName: 'Daniel Wright',
    contactEmail: 'daniel.wright@example.com',
    contactPhone: '+1 303-559-7743',
    contactAvatar: '/images/avatars/avatar-19.webp',
    baseAmount: 1699
  },
  {
    id: 'booking-091',
    packageSlug: 'dubai-luxury-city-break',
    packageTitle: 'Dubai Luxury City Break',
    packageImage: '/images/countries/uae/uae-1.webp',
    packageLocation: 'Dubai, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 1,
    travelDate: '2026-10-09',
    bookingRef: 'TRV-0201-ZEDY',
    totalAmount: 1999,
    paymentResult: { method: 'card', cardLast4: '8909' },
    bookedAt: '2026-08-12T20:50:00.000Z',
    status: 'cancelled',
    contactName: 'Avery Scott',
    contactEmail: 'avery.scott@example.com',
    contactPhone: '+1 602-338-1195',
    contactAvatar: '/images/avatars/avatar-20.webp',
    baseAmount: 1999
  },
  {
    id: 'booking-092',
    packageSlug: 'abu-dhabi-desert-safari',
    packageTitle: 'Abu Dhabi Desert Safari',
    packageImage: '/images/countries/uae/uae-2.webp',
    packageLocation: 'Abu Dhabi, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 3,
    travelDate: '2026-11-27',
    bookingRef: 'TRV-0202-SXRW',
    totalAmount: 4797,
    paymentResult: { method: 'card', cardLast4: '7627' },
    bookedAt: '2026-07-29T19:39:00.000Z',
    status: 'upcoming',
    contactName: 'Avery Scott',
    contactEmail: 'avery.scott@example.com',
    contactPhone: '+1 602-338-1195',
    contactAvatar: '/images/avatars/avatar-20.webp',
    baseAmount: 4797
  },
  {
    id: 'booking-093',
    packageSlug: 'dubai-marina-cruise-and-skyline',
    packageTitle: 'Dubai Marina Cruise & Skyline',
    packageImage: '/images/countries/uae/uae-3.webp',
    packageLocation: 'Dubai Marina, UAE',
    packageDays: 4,
    packageNights: 3,
    travelers: 1,
    travelDate: '2026-10-05',
    bookingRef: 'TRV-0203-KNKC',
    totalAmount: 2299,
    paymentResult: { method: 'upi' },
    bookedAt: '2026-06-28T11:02:00.000Z',
    status: 'upcoming',
    contactName: 'Avery Scott',
    contactEmail: 'avery.scott@example.com',
    contactPhone: '+1 602-338-1195',
    contactAvatar: '/images/avatars/avatar-20.webp',
    baseAmount: 2299
  },
  {
    id: 'booking-094',
    packageSlug: 'sharjah-heritage-walk',
    packageTitle: 'Sharjah Heritage Walk',
    packageImage: '/images/countries/uae/uae-4.webp',
    packageLocation: 'Sharjah, UAE',
    packageDays: 3,
    packageNights: 2,
    travelers: 1,
    travelDate: '2026-10-27',
    bookingRef: 'TRV-0204-SHKL',
    totalAmount: 999,
    paymentResult: { method: 'card', cardLast4: '6017' },
    bookedAt: '2026-08-30T18:02:00.000Z',
    status: 'cancelled',
    contactName: 'Avery Scott',
    contactEmail: 'avery.scott@example.com',
    contactPhone: '+1 602-338-1195',
    contactAvatar: '/images/avatars/avatar-20.webp',
    baseAmount: 999
  }
]
