// Type Imports
import type { Coupon } from '@/types/apps/coupon-types'

/**
 * ! The data below is used to seed the Coupons store. If you're using an ORM
 * ! (Object-Relational Mapping) or a database, you can replace this with your
 * ! own database queries inside the server action.
 *
 * ! The first four coupons (SUMMER20, MONSOON10, FIRST15, ANNI30) are seeded with
 * ! `isFeatured: true` — they're the public site homepage's "Special Offers" cards. That section
 * ! reads live from `useCouponsStore` (via `useCouponStore`'s cross-store sync, see
 * ! `src/store/use-coupon-store.ts`), capped at `MAX_FEATURED_COUPONS`, so featuring/unfeaturing a
 * ! coupon from Coupons & Promotions updates the homepage immediately.
 */
export const db: Coupon[] = [
  {
    id: 'coupon-001',
    code: 'SUMMER20',
    title: 'Summer Vibes Sale',
    description: 'Seasonal discount on all Asia getaways.',
    image: '/images/coupons/coupon-1.webp',
    discountType: 'percentage',
    appliesTo: 'beach',
    discountValue: 20,
    usageLimit: 500,
    usedCount: 342,
    validFrom: '2026-06-01',
    validUntil: '2026-09-30',
    isActive: true,
    isFeatured: true,
    createdAt: '2026-05-20',
    updatedAt: '2026-07-28'
  },
  {
    id: 'coupon-002',
    code: 'MONSOON10',
    title: 'Monsoon Sale',
    description: 'Extra savings on European escapes during monsoon season.',
    image: '/images/coupons/coupon-4.webp',
    discountType: 'percentage',
    appliesTo: 'all',
    discountValue: 10,
    usageLimit: 300,
    usedCount: 128,
    validFrom: '2026-07-01',
    validUntil: '2026-09-15',
    isActive: true,
    isFeatured: true,
    createdAt: '2026-06-15',
    updatedAt: '2026-07-20'
  },
  {
    id: 'coupon-003',
    code: 'FIRST15',
    title: 'First Booking Bonus',
    description: 'Welcome discount for first-time bookers.',
    image: '/images/coupons/coupon-3.webp',
    discountType: 'percentage',
    appliesTo: 'all',
    discountValue: 15,
    usageLimit: 1000,
    usedCount: 456,
    validFrom: '2026-01-01',
    validUntil: '2026-12-31',
    isActive: true,
    isFeatured: true,
    createdAt: '2025-12-20',
    updatedAt: '2026-07-15'
  },
  {
    id: 'coupon-004',
    code: 'ANNI30',
    title: 'Anniversary Sale',
    description: 'Once-a-year anniversary discount on getaways worldwide.',
    image: '/images/coupons/coupon-2.webp',
    discountType: 'percentage',
    appliesTo: 'all',
    discountValue: 30,
    usageLimit: 400,
    usedCount: 200,
    validFrom: '2026-06-15',
    validUntil: '2026-12-31',
    isActive: true,
    isFeatured: true,
    createdAt: '2026-03-15',
    updatedAt: '2026-08-01'
  },
  {
    id: 'coupon-005',
    code: 'SAFARI12',
    title: 'Safari Season Special',
    description: 'Discount on African safari tour packages.',
    image: '/images/coupons/coupon-4.webp',
    discountType: 'percentage',
    appliesTo: 'wildlife',
    discountValue: 12,
    usageLimit: 150,
    usedCount: 89,
    validFrom: '2026-05-01',
    validUntil: '2026-08-31',
    isActive: true,
    isFeatured: false,
    createdAt: '2026-04-18',
    updatedAt: '2026-07-30'
  },
  {
    id: 'coupon-006',
    code: 'WELCOME10',
    title: 'New Customer Welcome',
    description: 'Standing discount for newly registered customers.',
    discountType: 'percentage',
    appliesTo: 'all',
    discountValue: 10,
    usageLimit: 1000,
    usedCount: 734,
    validFrom: '2026-01-01',
    validUntil: '2026-12-31',
    isActive: true,
    isFeatured: false,
    createdAt: '2025-12-28',
    updatedAt: '2026-06-02'
  },
  {
    id: 'coupon-007',
    code: 'FLAT50',
    title: 'Flat $50 Off Bookings $500+',
    description: 'Flat-rate discount on bookings above $500.',
    discountType: 'fixed',
    appliesTo: 'all',
    discountValue: 50,
    usageLimit: 400,
    usedCount: 210,
    validFrom: '2026-03-01',
    validUntil: '2026-10-31',
    isActive: true,
    isFeatured: false,
    createdAt: '2026-02-20',
    updatedAt: '2026-07-18'
  },
  {
    id: 'coupon-008',
    code: 'WINTER25',
    title: 'Winter Getaway Deal',
    description: 'Winter season discount — window has closed.',
    discountType: 'percentage',
    appliesTo: 'adventure',
    discountValue: 25,
    usageLimit: 300,
    usedCount: 178,
    validFrom: '2025-12-01',
    validUntil: '2026-02-28',
    isActive: true,
    isFeatured: false,
    createdAt: '2025-11-15',
    updatedAt: '2026-02-28'
  },
  {
    id: 'coupon-009',
    code: 'HONEYMOON100',
    title: 'Honeymoon Special',
    description: 'Flat discount for honeymoon package bookings.',
    discountType: 'fixed',
    appliesTo: 'honeymoon',
    discountValue: 100,
    usageLimit: 100,
    usedCount: 45,
    validFrom: '2026-06-01',
    validUntil: '2026-12-31',
    isActive: true,
    isFeatured: false,
    createdAt: '2026-05-25',
    updatedAt: '2026-07-22'
  },
  {
    id: 'coupon-010',
    code: 'FLASH5',
    title: 'Flash Weekend Sale',
    description: 'One-week flash sale — already ended.',
    discountType: 'percentage',
    appliesTo: 'all',
    discountValue: 5,
    usageLimit: 5000,
    usedCount: 4890,
    validFrom: '2026-07-20',
    validUntil: '2026-07-27',
    isActive: true,
    isFeatured: false,
    createdAt: '2026-07-15',
    updatedAt: '2026-07-27'
  },
  {
    id: 'coupon-011',
    code: 'LOYALTY20',
    title: 'Loyalty Rewards',
    description: 'Paused while the loyalty program is being redesigned.',
    discountType: 'fixed',
    appliesTo: 'all',
    discountValue: 20,
    usageLimit: 600,
    usedCount: 12,
    validFrom: '2026-08-01',
    validUntil: '2026-11-30',
    isActive: false,
    isFeatured: false,
    createdAt: '2026-07-25',
    updatedAt: '2026-08-02'
  },
  {
    id: 'coupon-012',
    code: 'STUDENT15',
    title: 'Student Explorer Discount',
    description: 'Discount for verified student travelers.',
    discountType: 'percentage',
    appliesTo: 'all',
    discountValue: 15,
    usageLimit: 350,
    usedCount: 0,
    validFrom: '2026-09-01',
    validUntil: '2027-01-31',
    isActive: true,
    isFeatured: false,
    createdAt: '2026-08-01',
    updatedAt: '2026-08-01'
  }
]
